name: JsCoq's CI Action

on:
  push:
    branches:
    - 'v9.1'
    - 'v9.0'
    - 'v8.20'
    - 'v8.19'
    - 'v8.18'
    - 'v8.17\+lsp'
  pull_request:
    branches:
    - 'v9.1'
    - 'v9.0'
    - 'v8.20'
    - 'v8.19'
    - 'v8.18'
    - 'v8.17\+lsp'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - jscoq_arch: 32
            ocaml_compiler: "ocaml-variants.4.12.0+options,ocaml-option-32bit"
          - jscoq_arch: 64
            ocaml_compiler: "ocaml-base-compiler.4.12.0"
    env:
      OPAMJOBS: "2"
      OPAMROOTISOK: "true"
      OPAMYES: "true"
      NJOBS: "2"
      JSCOQ_ARCH: ${{ matrix.jscoq_arch }}
      OPAM_LINUX_URL: https://github.com/ocaml/opam/releases/download/2.3.0/opam-2.3.0-x86_64-linux
      OPAM_MACOS_URL: https://github.com/ocaml/opam/releases/download/2.3.0/opam-2.3.0-x86_64-darwin
      WASI_SDK_URL: https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
    runs-on: ubuntu-latest

    steps:
      # OPAM figures out everything but the libgmp-dev:i386
      # dependency, maybe worth fixing this upstream in the opam
      # repository
      - name: Install apt dependencies
        if: matrix.jscoq_arch == '32'
        run: |
          sudo apt-get install aptitude
          sudo dpkg --add-architecture i386
          sudo aptitude -o Acquire::Retries=30 update -q
          sudo aptitude -o Acquire::Retries=30 install gcc-multilib g++-multilib pkg-config libgmp-dev:i386 -y

      - name: 🔭 Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml_compiler}}
          dune-cache: true

      - name: 🐫🐪🐫 Get OCaml dependencies
        run: |
          ./etc/toolchain-setup.sh --"$JSCOQ_ARCH" --local --ci
          opam switch
          opam list
          opam config var root

      - name: 🚀 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: WASI Setup
        run: |
          wget --quiet -O/tmp/wasi-sdk.tar.gz ${WASI_SDK_URL}
          ( cd /opt && sudo tar xf /tmp/wasi-sdk.tar.gz && sudo ln -s wasi-sdk-* wasi-sdk )

      - name: Coq download, patching, and setup
        run: make coq-get

      - name: jsCoq build (JSOO)
        run: make jscoq

      - name: jsCoq build (WASM)
        run: make wacoq

      - name: jsCoq addons
        run: |
          set -e
          echo 'Building addons disabled...'
          # make addons

      - name: jsCoq test
        if: false
        run: |
          set -e
          echo 'Testing JsCoq disabled...'
          # EJGA: Disabled for now, we need to see how to update the CLI
          # npm install # EJGA: uggg, but otherwise this won't work.
          # make test

      - name: Prepare artifact
        run: make dist-artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jsCoq_${{ matrix.jscoq_arch }}_${{ github.sha }}
          path: _build/artifact
          compression-level: 9

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v4
      - name: 🚀 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Typecheck TypeScript Code
        run: |
          npm i
          npm run typecheck

  docker:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      REPOS_URL: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (no push atm)
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: etc/docker/Dockerfile
          context: etc/docker
          target: jscoq-addons
          push: false
          tags: jscoq/jscoq:latest
          build-args: |
            BRANCH=${{ env.BRANCH_NAME }}
            JSCOQ_REPO=https://github.com/${{ env.REPOS_URL }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
